### ISSUE TITLE
NY line doesn't appear on H1 timeframe

### ISSUE THREAD

**Issue by tymu** [IamAdamJowett/mt4-indicators#6]
![capture](https://cloud.githubusercontent.com/assets/589653/13376215/e238debe-ddbe-11e5-85b2-26b69177568a.JPG)

On lower time frame everything is right
![capture2](https://cloud.githubusercontent.com/assets/589653/13376220/12f8e6c0-ddbf-11e5-9d19-ff7bdacaaeb2.JPG)

**Comment by IamAdamJowett** [comment]
Hey @tymu my first feeling is because you are on an hourly chart trying to how a line on the half hour. On an hourly each increment of time (and so each candle) , starts on the hour, and placing lines essentially between two candles is not possible.

Only thing that could be done is placing it on the hour mark before or after the half hour, but then that is not accurate.

Thoughts?

**Comment by tymu** [comment]
Hi Adam, thank you for reply. Now i understand the issue, your explanation is logical. The great solution would be that in such cases indicator will take only hour variable and create a unique line which will be visible only on the H1 timeframe.
I think it's very difficult to create such a code.
